export enum CarsActionTypes {
  SET_CAR_POSTS = "cars/SET_CAR_POSTS",
  SET_IS_LOADING = "cars/SET_IS_LOADING",
  SET_ERROR = "cars/SET_ERROR",
  SET_SELECTED_CAR_POST = "cars/SET_SELECTED_CAR_POST",

  SET_IS_CHARACTERISTICS = "cars/SET_IS_CHARACTERISTICS",
  SET_BASE_IMG = "cars/SET_BASE_IMG",
  SET_SELECTED_OPTION = "cars/SET_SELECTED_OPTION",
  SET_ARRAY_OPTION = "cars/SET_ARRAY_OPTION",
  SET_ARRAY_OPTION_USING_EDIT = "cars/SET_ARRAY_OPTION_USING_EDIT",
}
